0: 0W 2: 0L 6: 0Q 14: 0B
.ENTRY 20
20: PUSHW 0XAE48 RPUTW -26 RGETW -29
29: PUSHL 0X147ACF25 RPUTL -36 RGETL -38
40: PUSHQ 0X134679ABDE014578 RPUTQ -46 RGETQ -49
55: PUSHB 0X58 RPUTB -46 RGETB -49
63:
        /* RGOTO RGOSUB RGOZ RPUSHA */

PUSHW 0X4145 PUSHL 0X1357FDBA PUSHQ 0X13579BDF0ECA8642 PUSHB 0X9C
        /* */

        /* CGETW CGETL CGETQ CGETB CPUTW CPUTL CPUTQ CPUTB */
        /* GOTO GOSUB GOZ */
        /* GETSW GETSL GETSQ GETSB PUTSW PUTSL PUTSQ PUTSB */
        /* GETFW GETFL GETFQ GETFB PUTFW PUTFL PUTFQ PUTFB */
        /* LGETSW LGETSL LGETSQ LGETSB LPUTSW LPUTSL LPUTSQ LPUTSB */
        /* LGETFW LGETFL LGETFQ LGETFB LPUTFW LPUTFL LPUTFQ LPUTFB */

PUSHW 31 PUSHW -20 ADDI
PUSHW 23 PUSHW 17 SUBI
PUSHW 12 PUSHW -9 MULI
PUSHW 31 PUSHW 7 DIVI
        /* ans = 0xb 0x6 0xff94 0x4; all as expected */
        /* test also types L F C ? */

PUSHW 0XCACA PUSHW 4 CSFTW
PUSHW 0XCACA PUSHW -3 CSFTW
PUSHW 0XCACA PUSHW 2 ASFTW
PUSHW 0XCACA PUSHW -3 ASFTW
        /* ans = 0xacac 0x5656 0x32b2 0x5650; all as expected */
        /* test also sizes L Q B ? */

PUSHW 0XCACA NOTW
PUSHW 0XCACA PUSHW 0XB26B ANDW
PUSHW 0XCACA PUSHW 0XB26B ORW
PUSHW 0XCACA PUSHW 0XB26B XORW
        /* ans = 0x3535 0x824a 0xfaeb 0x78a1; all as expected */
        /* test also sizes L Q B ? */

        /* TSTEQI TSTEQL TSTEQF TSTEQC TSTLTI TSTLTL TSTLTF TSTLTC */
        /* DUPW DUPL DUPQ DUPO SWAPW SWAPL SWAPQ SWAPO */
        /* CHSPS CHSPF NEWFR RESFR */
        /* ADRD CVTIL CVTIF CVTIC CVTLI ZEXWQ CVTLF CVTLC */
        /* CVTFI CVTFL ADRC CVTFC CVTCI CVTCL CVTCF ADRF */

HALT